import type { Metadata } from "next";
import {  Anuphan} from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import { Providers } from "./providers";


const AnuphanSan = Anuphan({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Music Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={AnuphanSan.className}
      >
        <Providers>
          <Navbar />
          <main className="p-4">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
